### ISSUE TITLE
climate station data 

### ISSUE THREAD

**Issue by mheilen** [rogerlew/wepppy#156]
The climate data pulled by WEPPcloud for Casa Grande Ruins AZ appears to be from another station. The climate for Casa Grande Ruins AZ is hot and arid. The average monthly data displayed correspond to a much cooler and wetter climate than is present at Casa Grande Ruins AZ:  

![image](https://user-images.githubusercontent.com/57507893/69356189-0a206180-0c51-11ea-911a-1ef0687be611.png)

If one builds the climate using Casa Grande Ruins AZ Station and the PRISM modified option, the returned summary data are presented as being from the Calhoun City MS station:

![image](https://user-images.githubusercontent.com/57507893/69356306-481d8580-0c51-11ea-93b1-7b70b66b460c.png)

**Comment by rogerlew** [comment]
Hi Michael,

Sorry for the delayed response. I missed your issue. This was indeed a bug. The routine that finds the par file matches based on the station id and it turns out Calhoun City is 221314.

I forked your project to here and was able to build the climates with the PRISM revision using the correct par file:
https://wepp1.nkn.uidaho.edu/weppcloud/runs/rlew-rock-ribbed-messaging/0/

Thanks for reporting this.

Roger

**Comment by mheilen** [comment]
Hi Roger,

Thanks for fixing that issue! I figured it was probably something along those lines. WEPPcloud is awesome, by the way.

Best,
Michael


Michael Heilen, Ph.D., RPA | Director, Center for the Study of Cultural Landscapes
Statistical Research, Inc. | 4306 Mountain View Drive, Haymarket, VA 20169
Office 571-248-2100 | Cell 703-501-3465 | www.sricrm.com<http://www.sricrm.com/>

Statistical Research, Inc. is a certified woman-owned small business that has provided Cultural Resource Management and Historic Preservation services since 1983.
