### ISSUE TITLE
Suggestions for legends

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#27]
1. Flip the color bar. Currently, when the sliding bar is at 0, the legend shows yellow. However, the legend bar shows yellow at 10000 mm. So I guess we need to flip the legend bar.
2. Change Gridded Soil Deposition/Loss to Gridded Soil Loss/Deposition (to be consistent with the above Soil Loss/Deposition).
3. The word "Gridded" appears above the check circle mark. We need to bring it on the same line. 
4. I believe Subrunoff should be Runoff. Subrunoff would imply lateral flow, which I don't think we are displaying, no?
5. How come we have Total P if we don't have it in the plot file?
6. Are the values in the legend per year or total? I think we should display them as mm/year; tonne/ha/year, kg/m2/year. 
7. Could we change the colors in the legend? 
Runoff:
0 = green; light blue in the middle; dark blue the highest value
Soil loss:
0 = green; light brown in the middle; dark brown the highest value, or
0 = green; light green/pink; red the highest value
Phosphorus:
0 = green; light orange in the middle; dark orange the highest value
Gridded soil loss:
negative = yellow; 0 = green; light green/pink; red the highest value

**Comment by rogerlew** [comment]
> 1. Flip the color bar. Currently, when the sliding bar is at 0, the legend shows yellow. However, the legend bar shows yellow at 10000 mm. So I guess we need to flip the legend bar.

The slider changes the maximum value (the clamping value). The legend bar gets rescaled based on the maximum value.

> 2. Change Gridded Soil Deposition/Loss to Gridded Soil Loss/Deposition (to be consistent with the above Soil Loss/Deposition).

I'm thinking everything should change (consistently) to Deposition/Loss since Loss is positive and Deposition is Negative. Thoughts?

> 3. The word "Gridded" appears above the check circle mark. We need to bring it on the same line.

It is a sub heading. Like "Hillslopes." There might eventually be more than 1 gridded output. Will make "Hillslopes" and "Gridded" bold or something so they stand out.

> 4. I believe Subrunoff should be Runoff. Subrunoff would imply lateral flow, which I don't think we are displaying, no?

I was wondering about this. I think I used subrunoff before because there was no runoff with the project I was using at the time. I can change this to Runoff.

> 6. Are the values in the legend per year or total? I think we should display them as mm/year; tonne/ha/year, kg/m2/year.

They are average values for each year. The old interface has /year for some, but not for runoff. Since the table tiles have "Average Annual" I don't think we need it.? I'd also have to extend the unitizer to accomadate for some of those.

? 7. Could we change the colors in the legend?

Yeah, those are easy to change, but the selection is limited. Here are the options:

![image](https://user-images.githubusercontent.com/3652906/37928686-9a8e236a-30f2-11e8-8435-5173d5e60d69.png)

We should stay away from rainbow, jet, and hsv.

Luminance sensitivity is highest for green, so we might want to stay away from that as the background color.

**Comment by marianadobre** [comment]
On Mon, Mar 26, 2018 at 12:42 PM, Roger Lew <notifications@github.com>
wrote:

>
>    1. Flip the color bar. Currently, when the sliding bar is at 0, the
>    legend shows yellow. However, the legend bar shows yellow at 10000 mm. So I
>    guess we need to flip the legend bar.
>
> The slider changes the maximum value (the clamping value). The legend bar
> gets rescaled based on the maximum value.
>
*Yes, I see it now. *

>
>    1. Change Gridded Soil Deposition/Loss to Gridded Soil Loss/Deposition
>    (to be consistent with the above Soil Loss/Deposition).
>
> I'm thinking everything should change (consistently) to Deposition/Loss
> since Loss is positive and Deposition is Negative. Thoughts?
>
*Ah! I see what you're saying. I guess mathematically you are correct. From
a user perspective they care about soil loss and rarely about deposition.
We can change it everywhere to soil deposition/loss for now and see if
anyone complains about it. :) As long as both legends are the same, I guess
we're good.  *

>
>    1. The word "Gridded" appears above the check circle mark. We need to
>    bring it on the same line.
>
> It is a sub heading. Like "Hillslopes." There might eventually be more
> than 1 gridded output. Will make "Hillslopes" and "Gridded" bold or
> something so they stand out.
>
*OK. It makes sense. Maybe we could make Hillslope and Gridded bold to
stand out? Or write them in different color?*

>
>    1. I believe Subrunoff should be Runoff. Subrunoff would imply lateral
>    flow, which I don't think we are displaying, no?
>
> I was wondering about this. I think I used subrunoff before because there
> was no runoff with the project I was using at the time. I can change this
> to Runoff.
>
*OK. Would we be able to plot lateral flow and baseflow? That would be
really cool. *

>
>    1. Are the values in the legend per year or total? I think we should
>    display them as mm/year; tonne/ha/year, kg/m2/year.
>
> They are average values for each year. The old interface has /year for
> some, but not for runoff. Since the table tiles have "Average Annual" I
> don't think we need it.? I'd also have to extend the unitizer to accomadate
> for some of those.
>
*Sounds good. *

> ? 7. Could we change the colors in the legend?
>
> Yeah, those are easy to change, but the selection is limited. Here are the
> options:
>
> [image: image]
> <https://user-images.githubusercontent.com/3652906/37928686-9a8e236a-30f2-11e8-8435-5173d5e60d69.png>
>
> We should stay away from rainbow, jet, and hsv.
>
> Luminance sensitivity is highest for green, so we might want to stay away
> from that as the background color.
>



*OK. How about if we try:*

*Runoff: winter*

*Deposition/Loss: portland*


*Phosphorus: current one, viridis*


*P.S. I love the tool for changing managements' cover. *

*M*

**Comment by marianadobre** [comment]
Or
*Deposition/Loss: coper*

**Comment by rogerlew** [comment]
I think those colors work. soil loss for hillslopes is working now.

https://wepp1.nkn.uidaho.edu/weppcloud/runs/f26c3690-c491-478f-90f9-f6710abb2618/lt-fire/

![image](https://user-images.githubusercontent.com/3652906/37947327-5ce94628-313f-11e8-9b3c-9c5688d2fbb4.png)

**Comment by marianadobre** [comment]
Awesome!

**Comment by rogerlew** [comment]
The portland map isn't ideal for the gridded deposition loss because the deposition is tends to be by the channels and the channels are blue, so it is hard to distinguish the channels from the depositions.

How about "electric?"

![image](https://user-images.githubusercontent.com/3652906/37982758-4ee2be44-31a6-11e8-9feb-d44723e9c1d9.png)

**Comment by marianadobre** [comment]
Yes, that will work.

**Comment by rogerlew** [comment]
Cool, let's go with that for now.

**Comment by rogerlew** [comment]
![image](https://user-images.githubusercontent.com/3652906/37993267-f044c504-31c2-11e8-8049-3b531fb29510.png)
