### ISSUE TITLE
Intensities in debris flow

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#71]
Rainfall intensities and total rainfall values are switched. 
Rainfall intensities should be (mm/hr) and Total rainfall should be (mm). Either we correct the names or the values in the table. Also, I think these values might be switched in the calculations. And I think there might be an error when the mm/hr calculation is done for under an hour versus over an hour. 

For example, in https://wepp1.nkn.uidaho.edu/weppcloud/runs/mdob4d03-c26c-44ed-bed3-3a3b644c7d6b/baer/

2 hr 15 minute displays 8 (33), which makes sense. 8 mm in 15 min --> 32 mm/hour
200 yrs 7 day displays 505 (3), doesn't make sense. It should be 3 (505) -->3 mm/hr x  24 hrs/day x 7 days = 504 mm total 

Also, would it be possible to allow the user to enter:
clay content
liquid limit
rainfall intensity (mm/hr)
total rainfall (mm)

Question: You said the interface takes the clay content directly from SSURGO/STATSGO. But if we continue with the interface after we run the debris flow, and if we are in PEP, it should use the PEP soils, right? Now it says the soils are not available when I try to open the soil files so I can't double check.

https://wepp1.nkn.uidaho.edu/weppcloud/runs/mdob4d03-c26c-44ed-bed3-3a3b644c7d6b/baer/

Sorry I dumped all in one issue here but I thought they are all related. :)

**Comment by rogerlew** [comment]
I and T are now swapped

user can specify clay content and liquid limit on debris flow results page.  When the user reruns the model those parameters get stored to the debris_flow.nodb.

There is also a calculator for user specified I and T values at the bottom of the page. It just runs in javascript on the page. The results don't get saved back to the server.

SSURGO/STATSGO soil building occurs for PEP before the general soils are implemented. The clay content is calculated from those soils. Since the debris flow model is completely independent from WEPP I think it still makes sense to use the SSURGO clay values. I added a build log for the clay calculation.
